[application]

# App (Project) Name
name = "Wallpaper UI"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]
[web.watcher]
[web.resource]
[web.resource.dev]
